GPU available: True (cuda), used: False
TPU available: False, using: 0 TPU cores
IPU available: False, using: 0 IPUs
HPU available: False, using: 0 HPUs
/users/yliang51/data/yliang51/envs/gaufre/lib/python3.7/site-packages/lightning/pytorch/trainer/setup.py:179: PossibleUserWarning: GPU available but not used. Set `accelerator` and `devices` using `Trainer(accelerator='gpu', devices=1)`.
  category=PossibleUserWarning,
Traceback (most recent call last):
  File "main.py", line 10, in <module>
    subclass_mode_data=True
  File "/users/yliang51/data/yliang51/envs/gaufre/lib/python3.7/site-packages/lightning/pytorch/cli.py", line 358, in __init__
    self._run_subcommand(self.subcommand)
  File "/users/yliang51/data/yliang51/envs/gaufre/lib/python3.7/site-packages/lightning/pytorch/cli.py", line 670, in _run_subcommand
    fn(**fn_kwargs)
  File "/users/yliang51/data/yliang51/envs/gaufre/lib/python3.7/site-packages/lightning/pytorch/trainer/trainer.py", line 609, in fit
    self, self._fit_impl, model, train_dataloaders, val_dataloaders, datamodule, ckpt_path
  File "/users/yliang51/data/yliang51/envs/gaufre/lib/python3.7/site-packages/lightning/pytorch/trainer/call.py", line 38, in _call_and_handle_interrupt
    return trainer_fn(*args, **kwargs)
  File "/users/yliang51/data/yliang51/envs/gaufre/lib/python3.7/site-packages/lightning/pytorch/trainer/trainer.py", line 639, in _fit_impl
    model, train_dataloaders=train_dataloaders, val_dataloaders=val_dataloaders, datamodule=datamodule
  File "/users/yliang51/data/yliang51/envs/gaufre/lib/python3.7/site-packages/lightning/pytorch/trainer/connectors/data_connector.py", line 139, in attach_data
    _check_dataloader_none(train_dataloaders, self._train_dataloader_source, self.trainer.state.fn)
  File "/users/yliang51/data/yliang51/envs/gaufre/lib/python3.7/site-packages/lightning/pytorch/trainer/connectors/data_connector.py", line 599, in _check_dataloader_none
    f"An invalid dataloader was passed to `Trainer.{trainer_fn}({prefix}dataloaders=...)`."
ValueError: An invalid dataloader was passed to `Trainer.fit(train_dataloaders=...)`. Either pass the dataloader to the `.fit()` method OR implement `def train_dataloader(self):` in your LightningModule/LightningDataModule.