## SLURM PROLOG ###############################################################
##    Job ID : 1055778
##  Job Name : debug_dnerf_D3G_test
##  Nodelist : gpu2261
##      CPUs : 1
##  Mem/Node : 16384 MB
## Directory : /oscar/data/jtompki1/yliang51/GaussianDiff/slurms
##   Job Started : Tue Mar 12 12:28:17 AM EDT 2024
###############################################################################
conda 23.1.0
/users/yliang51/data/yliang51/envs/gaufre/bin/python
/users/yliang51/data/yliang51/envs/gaufre/bin/pip
[rank: 0] Seed set to 0
GPU available: True (cuda), used: True
TPU available: False, using: 0 TPU cores
IPU available: False, using: 0 IPUs
HPU available: False, using: 0 HPUs
You are using a CUDA device ('NVIDIA RTX A6000') that has Tensor Cores. To properly utilize them, you should set `torch.set_float32_matmul_precision('medium' | 'high')` which will trade-off precision for performance. For more details, read https://pytorch.org/docs/stable/generated/torch.set_float32_matmul_precision.html#torch.set_float32_matmul_precision
[rank: 0] Seed set to 0
Initializing distributed: GLOBAL_RANK: 0, MEMBER: 1/1
----------------------------------------------------------------------------------------------------
distributed_backend=nccl
All distributed processes registered. Starting with 1 processes
----------------------------------------------------------------------------------------------------

Restoring states from the checkpoint path at output/base_dnerf_D3G/base/uex55sll/checkpoints/epoch=0-step=40000.ckpt
output path: ./output/base_dnerf_D3G
Setting up [LPIPS] perceptual loss: trunk [alex], v[0.1], spatial [on]
Loading model from: /users/yliang51/data/yliang51/envs/gaufre/lib/python3.9/site-packages/lpips/weights/v0.1/alex.pth
Reading Training Transforms
Reading Test Transforms
Generating random point cloud (100000)...
Traceback (most recent call last):
  File "/oscar/data/jtompki1/yliang51/GaussianDiff/main.py", line 6, in <module>
    cli = MyLightningCLI(
  File "/users/yliang51/data/yliang51/envs/gaufre/lib/python3.9/site-packages/lightning/pytorch/cli.py", line 388, in __init__
    self._run_subcommand(self.subcommand)
  File "/users/yliang51/data/yliang51/envs/gaufre/lib/python3.9/site-packages/lightning/pytorch/cli.py", line 679, in _run_subcommand
    fn(**fn_kwargs)
  File "/users/yliang51/data/yliang51/envs/gaufre/lib/python3.9/site-packages/lightning/pytorch/trainer/trainer.py", line 754, in test
    return call._call_and_handle_interrupt(
  File "/users/yliang51/data/yliang51/envs/gaufre/lib/python3.9/site-packages/lightning/pytorch/trainer/call.py", line 43, in _call_and_handle_interrupt
    return trainer.strategy.launcher.launch(trainer_fn, *args, trainer=trainer, **kwargs)
  File "/users/yliang51/data/yliang51/envs/gaufre/lib/python3.9/site-packages/lightning/pytorch/strategies/launchers/subprocess_script.py", line 105, in launch
    return function(*args, **kwargs)
  File "/users/yliang51/data/yliang51/envs/gaufre/lib/python3.9/site-packages/lightning/pytorch/trainer/trainer.py", line 794, in _test_impl
    results = self._run(model, ckpt_path=ckpt_path)
  File "/users/yliang51/data/yliang51/envs/gaufre/lib/python3.9/site-packages/lightning/pytorch/trainer/trainer.py", line 956, in _run
    self._checkpoint_connector._restore_modules_and_callbacks(ckpt_path)
  File "/users/yliang51/data/yliang51/envs/gaufre/lib/python3.9/site-packages/lightning/pytorch/trainer/connectors/checkpoint_connector.py", line 398, in _restore_modules_and_callbacks
    self.restore_model()
  File "/users/yliang51/data/yliang51/envs/gaufre/lib/python3.9/site-packages/lightning/pytorch/trainer/connectors/checkpoint_connector.py", line 275, in restore_model
    self.trainer.strategy.load_model_state_dict(
  File "/users/yliang51/data/yliang51/envs/gaufre/lib/python3.9/site-packages/lightning/pytorch/strategies/strategy.py", line 372, in load_model_state_dict
    self.lightning_module.load_state_dict(checkpoint["state_dict"], strict=strict)
  File "/users/yliang51/data/yliang51/envs/gaufre/lib/python3.9/site-packages/torch/nn/modules/module.py", line 2153, in load_state_dict
    raise RuntimeError('Error(s) in loading state_dict for {}:\n\t{}'.format(
RuntimeError: Error(s) in loading state_dict for GS3d:
	Missing key(s) in state_dict: "lpips.scaling_layer.shift", "lpips.scaling_layer.scale", "lpips.net.slice1.0.weight", "lpips.net.slice1.0.bias", "lpips.net.slice2.3.weight", "lpips.net.slice2.3.bias", "lpips.net.slice3.6.weight", "lpips.net.slice3.6.bias", "lpips.net.slice4.8.weight", "lpips.net.slice4.8.bias", "lpips.net.slice5.10.weight", "lpips.net.slice5.10.bias", "lpips.lin0.model.1.weight", "lpips.lin1.model.1.weight", "lpips.lin2.model.1.weight", "lpips.lin3.model.1.weight", "lpips.lin4.model.1.weight", "lpips.lins.0.model.1.weight", "lpips.lins.1.model.1.weight", "lpips.lins.2.model.1.weight", "lpips.lins.3.model.1.weight", "lpips.lins.4.model.1.weight". 
	Unexpected key(s) in state_dict: "_xyz", "_features_dc", "_features_rest", "_scaling", "_rotation", "_opacity". 
